# Numpy

In [44]:
import numpy as np

## Array Creation

In [45]:
a=np.array([1,2,3])
print(type(a))                  # Shows type

<class 'numpy.ndarray'>


In [46]:
print("Array :\n",np.array([1,2,3]))                    # Create a array from an object
print("Zero Array :\n",np.zeros((2,2)))                 # Create a 2X2 matrix with zeros
print("Ones Array :\n",np.ones((2,2)))                  # Create a 2X2 matri with ones

Array :
 [1 2 3]
Zero Array :
 [[0. 0.]
 [0. 0.]]
Ones Array :
 [[1. 1.]
 [1. 1.]]


In [47]:
print("Empty Array :\n",np.empty([2,2],dtype=int))      # Create a array of shape with out initializing entries
print("Array :\n",np.full((2,2),fill_value=2))          # Returns a array of given shape with fill_value
print("Array :\n",np.arange(0,7,2))                     # Returns a array of evenly spaced with given interval

Empty Array :
 [[         0 1072693248]
 [         0 1072693248]]
Array :
 [[2 2]
 [2 2]]
Array :
 [0 2 4 6]


In [48]:
print('Linspace \t:',np.linspace(1,2,5))    # Returns a evenly spaced numbers over a specified interval
print('Logspace \t:',np.logspace(2,3,5))    # Returns numbers spaced evenly on a log scale

Linspace 	: [1.   1.25 1.5  1.75 2.  ]
Logspace 	: [ 100.          177.827941    316.22776602  562.34132519 1000.        ]


## Array Manipulation
Consider a=np.arange(0,10)

In [49]:
a=np.arange(6)

In [50]:
print('Reshape :\n',np.arange(6).reshape((3, 2)))
print('Transpose : \n',np.arange(6).reshape((3,2)).transpose())

Reshape :
 [[0 1]
 [2 3]
 [4 5]]
Transpose : 
 [[0 2 4]
 [1 3 5]]


In [51]:
print("Concatenate :\n",np.concatenate((a,a),axis=0))
print('Stack :\n',np.stack((a,a),axis=0))
print('Stack :\n',np.stack((a,a),axis=1))

Concatenate :
 [0 1 2 3 4 5 0 1 2 3 4 5]
Stack :
 [[0 1 2 3 4 5]
 [0 1 2 3 4 5]]
Stack :
 [[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


In [52]:
print("Split :\n",np.split(a,3))
print("Flip :\n",np.flip(a))
print("Roll :\n",np.roll(a,shift=2))

Split :
 [array([0, 1]), array([2, 3]), array([4, 5])]
Flip :
 [5 4 3 2 1 0]
Roll :
 [4 5 0 1 2 3]


## Mathematical Functions
consider a=np.arange(6)

In [53]:
a=np.arange(6)
print("Sum \t\t:",np.sum(a))
print("Squareroot \t:",np.sqrt(a))
print("Sin \t\t:",np.sin(a))
print("Absolute \t:",np.abs(-a))
print("Exponent \t:",np.exp(a))

Sum 		: 15
Squareroot 	: [0.         1.         1.41421356 1.73205081 2.         2.23606798]
Sin 		: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Absolute 	: [0 1 2 3 4 5]
Exponent 	: [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


In [54]:
print("Natural Log \t:",np.log(a[1:]))
print("Sin inverse\t:",np.arcsin(np.linspace(0,1,5)))
print("Power \t\t:",np.power(a,2))

Natural Log 	: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sin inverse	: [0.         0.25268026 0.52359878 0.84806208 1.57079633]
Power 		: [ 0  1  4  9 16 25]


## Statistical Function
consider a=np.random.randint(1,100,16).reshape(4,4)

In [55]:
a=np.random.randint(1,100,16).reshape(4,4)
print(a)

[[24 56 66 78]
 [ 4  1 78  7]
 [53 86 71  3]
 [77 92 22 76]]


In [56]:
# Median 
print('Median \t\t\t:',np.median(a))
print("Median along 0 axis\t:",np.median(a,axis=0))
print("Median along 1 axis\t:",np.median(a,axis=1))

Median 			: 61.0
Median along 0 axis	: [38.5 71.  68.5 41.5]
Median along 1 axis	: [61.   5.5 62.  76.5]


In [57]:
# Standard Deviation
print("Standard Deviation \t\t:",np.std(a))
print("Standard Deviation along 0 axis\t:",np.std(a,axis=0))
print("Standard Deviation along 1 axis\t:",np.std(a,axis=1))

Standard Deviation 		: 32.4111766987871
Standard Deviation along 0 axis	: [27.78938646 36.02342988 21.92458666 36.03470549]
Standard Deviation along 1 axis	: [20.04993766 32.11308145 31.27598919 26.60239651]


In [58]:
# Histogram
print("Histogram \t\t:",np.histogram(a))

Histogram 		: (array([4, 0, 2, 0, 0, 1, 1, 2, 4, 2], dtype=int64), array([ 1. , 10.1, 19.2, 28.3, 37.4, 46.5, 55.6, 64.7, 73.8, 82.9, 92. ]))


In [59]:
# Mean 
print("Mean \t:",np.mean(a))
print("Mean along axis 0",np.mean(a,axis=0))
print("Mean along axis 1",np.mean(a,axis=1))

Mean 	: 49.625
Mean along axis 0 [39.5  58.75 59.25 41.  ]
Mean along axis 1 [56.   22.5  53.25 66.75]


In [60]:
# Percentile 
print("Percentile",np.percentile(a,100))
print("Percentile",np.percentile(a,100,axis=0))
print("Percentile",np.percentile(a,100,axis=1))

Percentile 92.0
Percentile [77. 92. 78. 78.]
Percentile [78. 78. 86. 92.]


In [61]:
# Mean
print("Mean \t\t\t:",np.mean(a))
print("Mean along axis 0 \t:",np.mean(a,axis=0))
print("Mean along axis 1 \t:",np.mean(a,axis=1))

Mean 			: 49.625
Mean along axis 0 	: [39.5  58.75 59.25 41.  ]
Mean along axis 1 	: [56.   22.5  53.25 66.75]


In [62]:
# Variance 
print("Variance \t\t:",np.var(a))
print("Variance along 0 axis\t:",np.var(a,axis=0))
print("Variance along 1 axis\t:",np.var(a,axis=1))

Variance 		: 1050.484375
Variance along 0 axis	: [ 772.25   1297.6875  480.6875 1298.5   ]
Variance along 1 axis	: [ 402.     1031.25    978.1875  707.6875]


In [63]:
# Corrcoef
print("Corrcoef",np.corrcoef(a))

Corrcoef [[ 1.          0.31295367 -0.3667784  -0.26810335]
 [ 0.31295367  1.          0.26496752 -0.98313218]
 [-0.3667784   0.26496752  1.         -0.13063146]
 [-0.26810335 -0.98313218 -0.13063146  1.        ]]


## Linear Algebra
Consider A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [64]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [65]:
A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [66]:
# Dot product
print("Dot product :\n",np.dot(A,B))

Dot product :
 [[19 22]
 [43 50]]


In [67]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [68]:
# Compute the inverse of matrix A
A_inv = np.linalg.inv(A)
print("Inverse of matrix A:")
print(A_inv)

Inverse of matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [69]:
# Compute the determinant of matrix A
det_A = np.linalg.det(A)
print("\nDeterminant of matrix A:", det_A)


Determinant of matrix A: -2.0000000000000004


In [70]:
# Solve a system of linear equations Ax = B
B_vector = np.array([5, 6])
x = np.linalg.solve(A, B_vector)
print("\nSolution to Ax = B:")
print(x)


Solution to Ax = B:
[-4.   4.5]


In [71]:
# Compute the eigenvalues and eigenvectors of matrix A
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of matrix A:")
print(eigenvalues)
print("\nEigenvectors of matrix A:")
print(eigenvectors)


Eigenvalues of matrix A:
[-0.37228132  5.37228132]

Eigenvectors of matrix A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [72]:
# Perform Singular Value Decomposition (SVD) on matrix B
U, S, V = np.linalg.svd(B)
print("\nSingular Value Decomposition (SVD) of matrix B:")
print("U:")
print(U)
print("S (singular values):")
print(S)
print("V (conjugate transpose):")
print(V)



Singular Value Decomposition (SVD) of matrix B:
U:
[[-0.59206014 -0.80589378]
 [-0.80589378  0.59206014]]
S (singular values):
[13.19003444  0.15162963]
V (conjugate transpose):
[[-0.65212545 -0.75811107]
 [ 0.75811107 -0.65212545]]


In [73]:
# Compute the QR decomposition of matrix B
Q, R = np.linalg.qr(B)
print("\nQR Decomposition of matrix B:")
print("Q:")
print(Q)
print("R:")
print(R)



QR Decomposition of matrix B:
Q:
[[-0.58123819 -0.81373347]
 [-0.81373347  0.58123819]]
R:
[[-8.60232527 -9.99729693]
 [ 0.         -0.23249528]]


In [74]:
# Norm of a vector
norm_v = np.linalg.norm(A)
print("Norm of vector v:", norm_v)
print()

# Frobenius norm of a matrix
norm_A = np.linalg.norm(A, 'fro')
print("Frobenius norm of Matrix A:", norm_A)

Norm of vector v: 5.477225575051661

Frobenius norm of Matrix A: 5.477225575051661


In [75]:
# Matrix Multiplication
print(np.matmul(A,B))

[[19 22]
 [43 50]]


In [76]:
# Cross Multiplication
print(np.cross(A,B))

[-4 -4]


In [77]:
# Inner Product
print(np.inner(A,B))

[[17 23]
 [39 53]]


## Random Sampling

In [78]:
a=np.arange(9)

In [79]:
print("Rand [0,1]\t:",np.random.rand(4))    
print("Randn \'Float\'\t:",np.random.randn(4))
print("Randint 'Integer b/w ranges'\t:",np.random.randint(0,4,4))
print("Random Choice \t:",np.random.choice(a))
print('Random Shuffle',np.random.shuffle(a),a)

Rand [0,1]	: [0.90340192 0.1374747  0.13927635 0.80739129]
Randn 'Float'	: [-1.40287272 -1.1425182  -0.34934272 -0.20889423]
Randint 'Integer b/w ranges'	: [2 0 1 2]
Random Choice 	: 7
Random Shuffle None [6 4 3 5 2 0 8 7 1]


In [80]:
print("Seed \t:",np.random.seed(1))
print("Permutation :",np.random.permutation(9))
print("Normal Gaussian Distribution \t:",np.random.normal(2))
print("Binomial Distribution :",np.random.binomial(10,0.5,10))
print("Exponential :",np.random.exponential(4))
print("Poisson :",np.random.poisson(a))

Seed 	: None
Permutation : [8 2 6 7 1 0 4 3 5]
Normal Gaussian Distribution 	: 1.4502538233401552
Binomial Distribution : [5 6 7 7 4 5 5 4 5 7]
Exponential : 2.4440928352447364
Poisson : [10  3  2  3  2  0  4  7  1]


## Bonus 

In [81]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
print("Broadcast_to :\n",np.broadcast_to([1,2,3],shape=[3,3]))  # Broadcasts an array to new shape
print("Delete \t\t:",np.delete(a,[1,3,5]))                      # Deletes elements along an axis of an array    
print("Insert \t\t:",np.insert(a,1,9))                          # Inserts value to the specified index
print("Append \t\t:",np.append(a,a))                            # Appends values to the end
print("Gradient \t:",np.gradient([1,3]))                        # Computes numerical gradient of the array

Broadcast_to :
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Delete 		: [0 2 4 6 7 8]
Insert 		: [0 9 1 2 3 4 5 6 7 8]
Append 		: [0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8]
Gradient 	: [2. 2.]


In [83]:
# Define two arrays
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.01, 3.00001])

# Check if elements are close within a default tolerance
print(np.isclose(a,b))

[ True False  True]


In [84]:
print("Identity Matrix :\n",np.eye(3))

Identity Matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


I hope you found this information helpful! <br>
Feel free to save this post for future reference.<br>
Let's continue to learn and grow together! <br>
<br>

[Rajendra Prasad](http://chlorinexxe.github.io/portfolio)
